env:
  global:
    - secure: XEnAF4sCmcy9WSBmZSbq8tP83kHSnGV4P2Mmn3kKi8h3NMvio6jULtC+zETqytCDpn30oQHOS6glKyB0gFDKB2Hijg9XUIry3yX6xjPKQSfxnkPzfwZXGp6UnU7F8zEbko30xlw+ijddkzsnqqeKqbFUkQl5wz0rncyVXbcX+HEZfLrW/GP4jDSLtWX/yeFyZb3Jatn2Dy5yvMKYLhautWM2CIIh0+BvPtdtzOzG7rBYjSgtVO0mbH5ghHPPnZL0hmCfc7Ae8GB77kRM53cigvMiLTt1Zq9SqQLJXLJmvI1NAn5QSQId8/3CyrWkPLHaP84oYTdqy/DaEACVOwUqgzSD9fmAWTcGOAbNkiuEmjiD7az/Tyh16JZIXAaXFNC924l36TRPHN7myHYi4k1UGXmVSkGsLTCYpSr1Wb6C/RckqV8p0YIZmX0iIbKpthcV+OP9XxKJDSSrv17lm/q6B3tn/Dbvwt91yk03lAQiey4HkkGqb6UJ+8TMSr+k6TcDnRcYqhylLKBJXO0h+VlfzN7c1dTcnL3jnW0jr/BY8gT+HElyp68OYi+q1OG9Yah/43z8CZbDEck7+hire/ep5x4BLmzMX+u+rhF4urPzGxGIKZvxsMymzAUAmRzW6ji16bE01G+5Fnomq2nKFOY4croYH9IPIkLmVu7SuKII8bo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.blocklist.de
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
