env:
  global:
    - secure: fVSac3aAQPM135SmnDQpPLDfFkTt2Rm0AW7VZvK6/N8DAk3kRIIgcVB2023vLOFp7xopkTRP9XKfrujslG8awTwqkbz1dD/+vZLLTTvEBPLsowYq/wXiLQJobD4U1hqf7kNdZvBrHduFAtqHWj0l1hCTIPD0KvYDl4eN/THjpUUe6H9M7QKI3el3X7y28sT1dphgHsNb6z1lLMcNuIUMpBKYm3aSUjmAgj5126+zsJAYPDzrg8fA78tqC4EBN/QGQiDVMnPxR3S6YP9mL986AFGVWk6FJK3mmll2QNpi9sPlpcXgwvHtdNyZB0Ciadlq9rLWnWAWT8AlxJ7Bi57mLh2hxJ/yAkIehcL0SL8w0bSVRYE6ztZDq+7Ey8a/kFrbCGupDnL8y9M/NeiKcn0Fyzr2b16eOG8dNxIbjRkKarG9wimTDpSaigD5ECdrytKXVN2ONpdQWvpTa43VyonuiAUpvLn01ygjgZh75oblPHbHsuKfdx1baXfuLXcHQg+Xof5ZxPuU+MVGLy1Q0Xha5hATLOkNSmxyiZGatbN/cDL3Oi4WkCSgn06Dl4dNAATU282w/HeyHFHosWo7jsuFL4BvvUyAJAvj5RVVdm/zqjPzmXRa5tsBB/PK6oFsz0YAJlwCMpjY7YToNsz67SgBsMeM3cF27r5Cb4equtjuuyw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.blocklist.de
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
