env:
  global:
    - secure: To0q/8zPsnYS8nUCTybF2l3uxHp3dUegJUFjPYZrEQjNZG9bqQ8Qb7e+xUNzZDzF4SU2S5QfuJokkWPFGtc8wGw/N/qYLUgfEzjq5hUTfNqm3ZlWBcecydcAvVNqo/3vEAZvWo0mjw+okq+/LNCS4vk3YsAgPzyadHrCHBJmZJRgrKz0HN3nYfgTyybtjzzKedYRya/GdGPZ2eXOoqaGtjDmF0IvGizX9rc0l+Jv7vfbh3uT0ATks5G4Lo9i8NnWkVVM390DsdVLwfTitYkvY+urgmLyq1mu2Fy74sId8NN7bOlnKmKTkCu99B1CWugBUqq+AMCDfGuzF7DufXhpOhiTCPf9qWLQcOKDVctbbFAzB1mD4VqtLj5VJBa43gIV8WPHnLitxOnPIRKn4aPq4trv6yGpZiRDCdSw7wR4Ke/K3gSJoI7wftL3WvrPWtVqtEe99fk0dtlHH2bU6xkwn3Vd55vyV1zcHwCYwlgewUFKbq1xuwxr4jXCCcI9sh9E2AGpIF1Jux55xiSsoS8GSgZLMRJIOuiwNxx4KxOEtc2D/Bc82TLyvjF2mlPQiL8OF9uigw62dbPQe5YuB8O6P4n9vR21otoAEfQBQCpoWaKcgqI9gnqudXGjVL4/3fGk4fpDrRskJT7BcqLRvakJ4tf1hxIZV8TtK6ME+25VV3k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/www.blocklist.de
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
